PooL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from . import views
from django.urls import path
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

home/urls.py
from . import views
from django.urls import path
# from .generate import generate
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('category/<str:category>', views.category, name='category'),
    path('post/', views.post, name='post'),
]
# generate()

userprofile/urls.py
from userprofile.views import UserUpdateView
from . import views
from django.urls import path

app_name = 'userprofile'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('update/<int:id>', views.update_ad, name='update_ad'),
    path('delete/<int:id>', views.delete_ad, name='delete_ad'),
    path('settings/<int:pk>', UserUpdateView.as_view(), name='settings'),
    path('settings/change-password/', views.change_password, name='change_password')
]

home/models.py
from django.db import models
from userprofile.models import MyUser
from django.utils import timezone
import datetime
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='media/icons')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

class Region(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Region'
        verbose_name_plural = 'Regions'

class Metro(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Metro station'
        verbose_name_plural = 'Metro stations'


class Ad(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, verbose_name='Region')
    metro = models.ForeignKey(Metro, on_delete=models.CASCADE, verbose_name='Meto station')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Categories')
    title = models.CharField(max_length=255, verbose_name='Title')
    desc = models.TextField(max_length=1000, verbose_name='Description')
    pub_date = models.DateTimeField(auto_now_add=True)
    lookups = models.IntegerField(default=0, verbose_name='Seen')
    is_paid = models.BooleanField(default=False, verbose_name='Mark as VIP')
    image = models.ImageField(default='default.jpg', blank=True, verbose_name='Photo')

    def __str__(self):
        return self.title

    @property
    def name(self):
        return self.user.first_name
    @property
    def phone_number(self):
        return self.user.phone
    @property
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    @property
    def publishing_date(self):
        if self.was_published_recently:
            return 'Today'
        else:
            pd = self.pub_date
            return pd.date()

    class Meta:
        verbose_name = 'Ad'
        verbose_name_plural = 'Ads'

home/forms.py
from django import forms
from .models import Ad
class Post(forms.ModelForm):
    class Meta:
        model = Ad
        exclude = ('pub_date','lookups','user',)
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control'}),
            'region': forms.Select(attrs={'class':'custom-select my-1 mr-sm-2'}),
            'metro': forms.Select(attrs={'class':'custom-select my-1 mr-sm-2'}),
            'category': forms.Select(attrs={'class': 'custom-select my-1 mr-sm-2'}),
            'desc': forms.Textarea(attrs={'class':'form-control','rows':'3'}),
            'is_paid': forms.CheckboxInput(attrs={'class':'form-check-input'}),
            'image': forms.FileInput(attrs={'class':'custom-file-input', 'multiple':False})
        }

home/views.py
from django.shortcuts import render
from .models import Ad, Category, Region
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import Post
from django.utils.text import capfirst
from django.conf import settings
# Create your views here.
def home(request):
    ads_list = Ad.objects.all().order_by('-pub_date')
    return listing(request, ads_list)

def listing(request, items, q_data=''):
    categories = Category.objects.all()
    regions = Region.objects.all()
    paginator = Paginator(items, 25)  # Show 25 contacts per page
    page = request.GET.get('page')
    try:
        ads = paginator.get_page(page)
    except PageNotAnInteger:
        ads = paginator.get_page(1)
    except EmptyPage:
        ads = paginator.get_page(paginator.num_pages)
    context = {'ads': ads, 'categories': categories, 'regions': regions, 'q_data':q_data}
    return render(request, 'home/index.html', context=context)

def search(request):
    q = request.GET.get('query')
    if q:
        ads_list = Ad.objects.filter(
            Q(title__icontains=q)|
            Q(desc__icontains=q)
        ).distinct().order_by('-pub_date')
        return listing(request, ads_list, q_data=q)
    else:
        return home(request)

def detail(request, id):
    ad = Ad.objects.get(pk=id)
    ad.lookups+=1
    ad.save()
    return render(request,'detail/detail.html',{'ad':ad})

def category(request, category):
    ads_list = Ad.objects.filter(category__name=category).order_by('-pub_date')
    return listing(request, ads_list, q_data=category)

def post(request):
    if request.method == 'POST':
        form = Post(request.POST, request.FILES or None)
        if request.user.is_authenticated:
            if form.is_valid():
                Ad.objects.create(
                    user=request.user,
                    region=form.cleaned_data['region'],
                    metro=form.cleaned_data['metro'],
                    category=form.cleaned_data['category'],
                    title=capfirst(form.cleaned_data['title'].lower()),
                    desc=capfirst(form.cleaned_data['desc'].lower()),
                    is_paid=form.cleaned_data['is_paid'],
                    image=form.cleaned_data['image']
                )
                return HttpResponseRedirect(reverse('home:home', current_app='home'))
            else:
                error = 'Жарнаманы жайгаштыруу ийгиликсиз аяктады/something went wrong'
                return render(request, 'post/post.html', {'form': form,'error':error})
        else:
            return HttpResponseRedirect(reverse('accounts:signup', current_app='accounts'))
    else:
        if request.user.is_authenticated:
            if len(Ad.objects.filter(user=request.user)) < settings.AD_NUM_PER_USER:
                form = Post()
                return render(request, 'post/post.html', {'form':form})
            else:
                return render(request,'post/limitover.html',{'limit':settings.AD_NUM_PER_USER})
        else:
            return HttpResponseRedirect(reverse('accounts:signup', current_app='accounts'))

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>PooL</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge">
	      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'home/assets/icons/css/font-awesome.min.css'%}">
        <link rel="stylesheet" href="{% static 'home/css/style.css'%}">
    </head>

    <body>
        {% include 'home/header.html' %}
      <div class="bg-img">
        <div class="bg-blur jumbotron px-0">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-12 col-lg-10">
                <h1 class="h2 text-light mb-3">Post and find ads easily!</h1>
                {% block search_box %}

                {% endblock %}
              </div>
            </div>
        </div>
      </div>
    </div><!--hero-->
            <div class="container mb-4">
              <div class="post-button text-right fixed-bottom px-4 mb-4">
                  <a href="#" class="btn btn-primary btn-lg rounded-circle"><i class="fa fa-pencil" aria-hidden="true"></i></a>
              </div>
              <div class="row justify-content-center">
                <div class="col-12 col-lg-10">
                  <ul class="row p-0 feature-list">
                    {% block categories_block %}
                    
                    {% endblock %}
                   </ul>
                </div>
              </div>
              <div class="row mt-sm-4">
                <div class="col-12 col-lg-8">
                    <div class="list-group">
                      {% block listing_header %}

                      {% endblock %}

                      {% block listing %}

                      {% endblock %}

                    </div>
                    {% block pagination %}

                    {% endblock %}
                </div><!-- col-12 -->
                  <div class="col-12 col-lg-4 pool-sidebar">
                      {% block sidebar %}

                      {% endblock %}
                  </div>
                </div><!--row-->
                <footer class="pt-4 my-md-5 pt-md-5 border-top">
                  <div class="row font-size-body">
                    <div class="col-12 col-md">
                      <strong class="d-block mb-2 text-muted">PooL</strong>
                      <small class="d-block mb-3 text-muted">© 2017-2018</small>
                    </div>
                    <div class="col-6 col-md">
                      <h5>Features</h5>
                      <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Cool stuff</a></li>
                        <li><a class="text-muted" href="#">Random feature</a></li>
                        <li><a class="text-muted" href="#">Team feature</a></li>
                        <li><a class="text-muted" href="#">Stuff for developers</a></li>
                        <li><a class="text-muted" href="#">Another one</a></li>
                        <li><a class="text-muted" href="#">Last time</a></li>
                      </ul>
                    </div>
                    <div class="col-6 col-md">
                      <h5>Resources</h5>
                      <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Resource</a></li>
                        <li><a class="text-muted" href="#">Resource name</a></li>
                        <li><a class="text-muted" href="#">Another resource</a></li>
                        <li><a class="text-muted" href="#">Final resource</a></li>
                      </ul>
                    </div>
                    <div class="col-6 col-md">
                      <h5>About</h5>
                      <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Team</a></li>
                        <li><a class="text-muted" href="#">Locations</a></li>
                        <li><a class="text-muted" href="#">Privacy</a></li>
                        <li><a class="text-muted" href="#">Terms</a></li>
                      </ul>
                    </div>
                  </div>
                </footer>
            </div><!--container-->
        <script src="{% static "home/js/jquery.min.js" %}"></script>
        <script src="{% static "home/js/popper.min.js" %}"></script>
        <script src="{% static "home/js/bootstrap.min.js" %}"></script>
        <script src="{% static "home/js/holder.min.js" %}"></script>
{#        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>#}
        <script src="{% static "home/js/main.js" %}" type="text/javascript"></script>
    </body>
</html>

home/templates/home/header.html
      <header>
        <div class="container">
          <nav class="navbar navbar-expand-lg navbar-light pr-0 pl-0">
              <a class="navbar-brand" href="{% url 'home:home' %}">
                <!-- <img class="d-inline-block" style="height:1rem;" src="../assets/discover.svg" alt=""> -->
                <h3 class="m-0 p-0 text-primary"><strong>PooL</strong></h3>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                  <!-- <span class="navbar-toggler-icon"></span> -->
                  <i class="fa fa-bars" aria-hidden="true"></i>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav ml-auto">
                      {% if request.path != '/userprofile/' %}
                          {% if request.user.is_authenticated %}

                          <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">
                                  <img class="avatar" src="{{ request.user.avatar.url }}" alt="me">
                                  <span>{{ request.user.first_name }}</span>
                              </a>
                              <div class="dropdown-menu">
                                  <a class="dropdown-item" href="{% url 'userprofile:profile' %}"><i class="mr-1 fa fa-user"></i>Cabinet</a>
                                  <a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="mr-1 fa fa-sign-out"></i>Log out</a>
                              </div>
                          </li>
                          <li class="nav-item">
                          <span class="nav-link">
                              <a href="#" class="btn btn-sm btn-success">
                                  <i class="fa fa-rub mr-1" aria-hidden="true"></i><span>{{ request.user.balance }}</span>
                              </a>
                          </span>
                          </li>

                          {% else %}
                              <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">
                                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                                <span>Account</span>
                            </a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign up</a>
                                <a class="dropdown-item" href="{% url 'accounts:login' %}">Sign in</a>
                            </div>
                            </li>
                          {% endif %}
                      {% endif %}
                      {% if request.path != '/post/' %}
                      <li class="nav-item">
                          <a class="nav-link" href="{% url 'home:post' %}">
                            <button class="text-light btn btn-sm btn-primary" type="button">Post and ad</button>
                          </a>
                      </li>
                      {% endif %}
                  </ul>
              </div>
          </nav>
        </div>
      </header>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block search_box %}
<div class="search-box">
  <form action="{% url 'home:search' %}" method="get ">
  {% csrf_token %}
    <div class="input-group input-group-lg mb-3" id="input-group">
      <div class="input-group-prepend">
          <select class="btn btn-light" id="region-select" name="region">
            <option selected value="all">Region</option>
            {% for region in regions %}
             <option value="{{ region.name }}">{{ region.name }}</option>
            {% endfor %}

          </select>
      </div>
      <div class="input-group-prepend">
        <select class="btn btn-light" id="category-select" name="category">
          <option selected value="all">Category</option>
          {% for category in categories %}
            <option value="{{ category.name }}">{{ category.name }}</option>
          {% endfor %}

        </select>
      </div>
      <input type="text" name='query' class="form-control" autofocus placeholder="Search">
      <div class="input-group-append">
        <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
      </div>
    </div>
  </form>
</div>
{% endblock %}

{% block categories_block %}
{% for category in categories %}
<li class="col-6 col-md-4 mb-4">
  <a href="{% url 'home:category' category.name %}" class="category-items card card-link" style="color:#808080">
   <div class="card-body d-flex flex-row justify-content-center align-items-center">
     <img src="{{ category.image.url }}" alt="{{ category.name }}" class="mr-2 d-inline-block icon"> {{ category.name }}
   </div>
  {% if category.name == q_data %}
       <div class="bg-primary pb-1 w-100"></div>
  {% endif %}
 </a>
</li>
{% endfor %}
{% endblock %}

{% block listing_header %}
{% if ads %}
    <div class="list-group-item bg-secondary border-0">Recent ads</div>
{% else %}
    <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
      <strong>No ads found</strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
{% endif %}
{% endblock %}

{% block listing %}
{% for ad in ads %}
<a href="{% url 'home:detail' ad.pk %}" class="list-group-item list-group-item-action border-secondary">
    <h5 class="font-size-header mb-1">{{ ad.title|truncatewords:"5"}}</h5>
    <p class="text-muted font-size-body mb-2">{{ ad.desc|truncatewords:"10"}}</p>
    <div class="text-muted font-size-footer">
      <span class="mr-2 d-inline-block"><i class="fa fa-clock-o mr-1" aria-hidden="true"></i>{{ ad.publishing_date}}</span>
      <span class="mr-2 d-inline-block"><i class="fa fa-map-marker mr-1" aria-hidden="true"></i>{{ ad.region }}<i style="font-size: 5px!important; vertical-align: middle;" class="fa fa-circle mx-1" aria-hidden="true"></i>{{ ad.metro }}</span>
      <span class="mr-2 d-inline-block"><i class="fa fa-user mr-1" aria-hidden="true"></i>{{ ad.name }}</span>
      {% if ad.is_paid %}
          <span class="mr-2 d-inline-block"><i class="fa fa-star text-warning"></i></span>
      {% endif %}
    </div>
</a>
{% endfor %}
{% endblock %}


{% block pagination %}
{% if ads %}
{% include 'home/pagination.html' %}
{% endif %}
{% endblock %}


{% block sidebar %}
    <img data-src="holder.js/100px50p?auto=yes&random=yes&text=Your ad goes here" alt="ad">
    <img data-src="holder.js/100px50p?auto=yes&random=yes&text=Your ad goes here" alt="ad" class="mt-3">
{% endblock %}

home/templates/home/pagination.html
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center my-4">
    {% if ads.has_previous %}
        <li class="page-item">
         <a class="page-link" href="?page={{ ads.number|add:-1 }}&query={{ q_data }}" tabindex="-1">
          <i class="fa fa-chevron-left" aria-hidden="true"></i>
         </a>
        </li>
    {% else %}
        <li class="page-item disabled">
         <span class="page-link" tabindex="-1">
          <i class="fa fa-chevron-left" aria-hidden="true"></i>
         </span>
        </li>
    {% endif %}
    <li class="page-item"><span class="page-link">{{ ads.number }} of {{ ads.paginator.num_pages }}</span></li>
    {% if ads.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ ads.number|add:1 }}&query={{ q_data }}">
            <i class="fa fa-chevron-right" aria-hidden="true"></i>
          </a>
        </li>
    {% else %}
        <li class="page-item disabled">
          <span class="page-link">
            <i class="fa fa-chevron-right" aria-hidden="true"></i>
          </span>
        </li>
    {% endif %}
  </ul>
</nav>