PooL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from . import views
from django.urls import path
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

home/urls.py
from . import views
from django.urls import path
# from .generate import generate
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('category/<str:category>', views.category, name='category'),
    path('post/', views.post, name='post'),
]
# generate()

userprofile/urls.py
from userprofile.views import UserUpdateView
from . import views
from django.urls import path

app_name = 'userprofile'
urlpatterns = [
    path('', views.profile, name='profile'),
    path('update/<int:id>', views.update_ad, name='update_ad'),
    path('delete/<int:id>', views.delete_ad, name='delete_ad'),
    path('settings/<int:pk>', UserUpdateView.as_view(), name='settings'),
    path('settings/change-password/', views.change_password, name='change_password')
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class MyUser(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(blank=True,max_length=100, null=True, unique=False)
    balance = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    phone = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(default='avatars/avatar.svg', verbose_name='Аватар', upload_to='avatars')
    REQUIRED_FIELDS = ['first_name','username']
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

userprofile/forms.py
from django import forms

from userprofile.models import MyUser


class UserSettingsForm(forms.ModelForm):
    class Meta:
        model = MyUser
        fields = ('avatar', 'first_name',)

userprofile/views.py
from django.shortcuts import render
from django.views.generic import UpdateView

from home.models import Ad
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth import update_session_auth_hash
# Create your views here.
from userprofile.forms import *
from .models import MyUser


def profile(request):
    if request.user.is_authenticated:
        user = request.user
        ads = Ad.objects.filter(user=user).order_by('-pub_date')
        return render(request, 'profile/profile.html', {'user': user, 'ads': ads})
    return HttpResponseRedirect(reverse('accounts:signup', current_app='accounts'))


def update_ad(request, id):
    if request.user.is_authenticated:
        user = request.user
        ads = Ad.objects.filter(user=user).order_by('-pub_date')
        ad = ads.get(pk=id)
        ad.pub_date = timezone.now()
        ad.save()
        return render(request, 'profile/profile.html', {'user': user, 'ads': ads})


def delete_ad(request, id):
    if request.user.is_authenticated:
        user = request.user
        ads = Ad.objects.filter(user=user).order_by('-pub_date')
        ad = ads.get(pk=id)
        ad.delete()
        return render(request, 'profile/profile.html', {'user': user, 'ads': ads})


class UserUpdateView(UpdateView):
    model = MyUser
    form_class = UserSettingsForm
    template_name = 'profile/settings.html'

    def get_success_url(self):
        return self.request.path

    def form_invalid(self, form):
        message = ''
        for error in form.errors:
            message+=error
        return JsonResponse(dict(success=False, message=message))

def settings(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = UserSettingsForm(data=request.POST)
            if form.is_valid():
                user = request.user
                user.first_name = form.cleaned_data['first_name']
                user.avatar = request.FILES['avatar']
                user.save()
                # user = MyUser.objects.get(email=request.user)
                # user.first_name = form.cleaned_data['first_name']
                # user.avatar = form.cleaned_data['avatar']
                # user.save()
        form = UserSettingsForm()
        return render(request, 'profile/settings.html', locals())
    return HttpResponseRedirect(reverse('accounts:signup', current_app='accounts'))


def change_password(request):
    return HttpResponseRedirect(reverse('home:home', current_app='home'))

userprofile/templates/profile/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru" class="h-100">
    <head>
        <title>PooL</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge">
	      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'userprofile/assets/icons/css/font-awesome.min.css'%}">
        <link rel="stylesheet" href="{% static 'userprofile/css/animate.css'%}">
        <link rel="stylesheet" href="{% static 'userprofile/css/style.css'%}">
    </head>

    <body class="h-100">
        {% include 'home/header.html' %}
      <div class="container" style="min-height:100%">
        <div class="row mt-3">
          <div class="col-12 col-md-4 mb-3">
            <div class="card mb-3 profile-card">
              <img class="card-img-top profile-bg" src="https://cdn.pixabay.com/photo/2016/05/27/19/06/background-1420464_960_720.jpg" alt="Card image cap">
              <div class="card-body position-relative text-center">
                    <div class="profile-img" style="background: #ffffff;">
                        <div class="w-100 position-relative" style="padding-bottom: 100%;">
                            <div class="position-absolute w-100 h-100">
                                <img class="img-fluid rounded-circle d-inline-block h-100 w-100" src="{{ request.user.avatar.url }}" alt="me">
                            </div>
                        </div>
                    </div>
                <h5 class="card-title">{% block namefield %}User{% endblock %}</h5>
                <p class="card-text font-size-body">
                  <span class="d-block"><i class="fa fa-envelope-o mr-2" aria-hidden="true"></i>{% block emailfield %}qwerty@email.com{% endblock %}</span>
                </p>
                <small>
                  <a href="{% url 'accounts:logout' %}" class="text-muted mr-2 d-inline-block"><i class="mr-1 fa fa-sign-out"></i>Log out</a>
                  <a href="{% url 'userprofile:settings' request.user.pk %}" class="text-muted d-inline-block settings-btn"><i class="mr-1 fa fa-cog"></i>Settings</a>
                </small>

              </div>
            </div>
          </div>
          <div class="col-12 col-md-8 mb-3">
            <ul class="list-group mb-3">
                {% block listing_header %}

                {% endblock %}
                {% block listing %}

                {% endblock %}
            </ul>
          </div>
        </div>
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
          <div class="row font-size-body">
            <div class="col-12 col-md">
              <strong class="d-block mb-2 text-muted">PooL</strong>
              <small class="d-block mb-3 text-muted">© 2017-2018</small>
            </div>
            <div class="col-6 col-md">
              <h5>Features</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Cool stuff</a></li>
                <li><a class="text-muted" href="#">Random feature</a></li>
                <li><a class="text-muted" href="#">Team feature</a></li>
                <li><a class="text-muted" href="#">Stuff for developers</a></li>
                <li><a class="text-muted" href="#">Another one</a></li>
                <li><a class="text-muted" href="#">Last time</a></li>
              </ul>
            </div>
            <div class="col-6 col-md">
              <h5>Resources</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Resource</a></li>
                <li><a class="text-muted" href="#">Resource name</a></li>
                <li><a class="text-muted" href="#">Another resource</a></li>
                <li><a class="text-muted" href="#">Final resource</a></li>
              </ul>
            </div>
            <div class="col-6 col-md">
              <h5>About</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Locations</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
              </ul>
            </div>
          </div>
        </footer>
      </div><!--container-->
      <script src="{% static "userprofile/js/jquery.min.js" %}"></script>
        <script src="{% static "userprofile/js/popper.min.js" %}"></script>
        <script src="{% static "userprofile/js/bootstrap.min.js" %}"></script>
      <script src="{% static "userprofile/js/main.js" %}" type="text/javascript"></script>
    </body>
</html>

userprofile/templates/profile/profile.html
{% extends 'profile/base.html' %}
{% block namefield %}
    {{ user.first_name }}
{% endblock %}

{% block emailfield %}
    {{ user.email }}
{% endblock %}

{% block listing_header %}
    {% if ads%}
        <div class="list-group-item bg-secondary border-0">
            Your ads
        </div>
    {% else %}
        <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
          <strong>You have no ads yet</strong>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    {% endif %}
{% endblock %}

{% block listing %}
{% for ad in ads %}
<li class="list-group-item">
<a href="{% url 'home:detail' ad.pk %}" class="list-item-link">
  <h5 class="mb-1 font-size-header">{{ ad.title|truncatewords:"5" }}</h5>
  <p class="mb-1 font-size-body">{{ ad.desc|truncatewords:"10" }}</p>
</a>
<div class="clearfix text-muted">
  <small class="d-inline-block mr-2"><i class="fa fa-clock-o mr-1" aria-hidden="true"></i>{{ ad.publishing_date }}</small>
  <small class="d-inline-block mr-2"><i class="fa fa-folder-open-o mr-1" aria-hidden="true"></i>{{ ad.category }}</small>
  <small class="d-inline-block"><i class="fa fa-eye mr-1" aria-hidden="true"></i>{{ ad.lookups }}</small>
  <div class="dropdown float-right">
    <button class="btn btn-outline-primary action-btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
    </button>
    <div class="dropdown-menu dropdown-menu-right">
      <a class="dropdown-item" href="{% url 'userprofile:update_ad' ad.pk %}">Refresh</a>
      <a class="dropdown-item" href="{% url 'userprofile:delete_ad' ad.pk %}">Delete</a>
    </div>
  </div>
</div>
</li>
{% endfor %}
{% endblock %}

userprofile/templates/profile/settings.html
{% load static widget_tweaks %}
<!DOCTYPE html>
<html lang="ru" class="h-100">
    <head>
        <title>PooL</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge">
	      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'userprofile/assets/icons/css/font-awesome.min.css'%}">
        <link rel="stylesheet" href="{% static 'userprofile/css/animate.css'%}">
        <link rel="stylesheet" href="{% static 'userprofile/css/style.css'%}">
    </head>

    <body class="h-100">
        {% include 'home/header.html' %}
      <div class="container" style="min-height:100%">
        <div class="row justify-content-center">
            <div class="col-md-8 py-5">

                <form action="{% url 'userprofile:settings' request.user.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group text-center">
                    <img src="{{ user.avatar.url }}" alt="" class="img-responsive d-inline-block">
                </div>
                <div class="form-group">
                    <label for="password">Аватар</label>
                    {% render_field form.avatar class='form-control' %}
                 </div>
                 <div class="form-group">
                    <label for="password">Имя</label>
                    {% render_field form.first_name  class='form-control' %}
                  </div>
                  <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>

                {% if text %}
                    <div class="card mt-4">
                    <div class="card-body">
                        {{ user }}
                    </div>
                </div>
                {% endif %}

            </div>
        </div>


        <footer class="pt-4 my-md-5 pt-md-5 border-top">
          <div class="row font-size-body">
            <div class="col-12 col-md">
              <strong class="d-block mb-2 text-muted">PooL</strong>
              <small class="d-block mb-3 text-muted">© 2017-2018</small>
            </div>
            <div class="col-6 col-md">
              <h5>Features</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Cool stuff</a></li>
                <li><a class="text-muted" href="#">Random feature</a></li>
                <li><a class="text-muted" href="#">Team feature</a></li>
                <li><a class="text-muted" href="#">Stuff for developers</a></li>
                <li><a class="text-muted" href="#">Another one</a></li>
                <li><a class="text-muted" href="#">Last time</a></li>
              </ul>
            </div>
            <div class="col-6 col-md">
              <h5>Resources</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Resource</a></li>
                <li><a class="text-muted" href="#">Resource name</a></li>
                <li><a class="text-muted" href="#">Another resource</a></li>
                <li><a class="text-muted" href="#">Final resource</a></li>
              </ul>
            </div>
            <div class="col-6 col-md">
              <h5>About</h5>
              <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Team</a></li>
                <li><a class="text-muted" href="#">Locations</a></li>
                <li><a class="text-muted" href="#">Privacy</a></li>
                <li><a class="text-muted" href="#">Terms</a></li>
              </ul>
            </div>
          </div>
        </footer>
      </div><!--container-->
      <script src="{% static "userprofile/js/jquery.min.js" %}"></script>
        <script src="{% static "userprofile/js/popper.min.js" %}"></script>
        <script src="{% static "userprofile/js/bootstrap.min.js" %}"></script>
      <script src="{% static "userprofile/js/main.js" %}" type="text/javascript"></script>
    </body>
</html>