PooL/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from . import views
from django.urls import path
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

home/urls.py
from . import views
from django.urls import path
# from .generate import generate
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('detail/<int:id>', views.detail, name='detail'),
    path('category/<str:category>', views.category, name='category'),
    path('post/', views.post, name='post'),
]
# generate()

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
class CreateUserForm(forms.Form):
    first_name = forms.CharField(max_length=50,min_length=2,widget=forms.TextInput(attrs={'class':'edge-bottom form-control','autofocus':'','placeholder':'name','required':''}))
    email = forms.EmailField(max_length=100, widget=forms.EmailInput(attrs={'class':'edge-top-bottom form-control','placeholder':'email','required':''}))
    password = forms.CharField(max_length=255,min_length=6, widget=forms.PasswordInput(attrs={'class':'edge-top form-control','placeholder':'password','required':''}))


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=100, widget=forms.EmailInput(attrs={'class':'edge-bottom form-control','placeholder':'email', 'autofocus':'','required':''}))
    password = forms.CharField(max_length=255, widget=forms.PasswordInput(attrs={'class':'edge-top form-control','placeholder':'password','required':''}))

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import CreateUserForm, LoginForm
from userprofile.models import MyUser
from django.utils.text import capfirst
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = CreateUserForm(data=request.POST)
        if form.is_valid():
            print(form.is_valid())
            try:
                MyUser.objects.get(email=form.cleaned_data['email'])
                return render(request, 'signup/signup.html', {'form': form, 'msg': 'User exists'})
            except:
                MyUser.objects.create_user(
                    username=capfirst(form.cleaned_data['first_name'].lower()),
                    email=form.cleaned_data['email'],
                    first_name=capfirst(form.cleaned_data['first_name'].lower()),
                    password=form.cleaned_data['password'],
                    balance = 300
                )
                user = authenticate(email=form.cleaned_data['email'],
                                    password=form.cleaned_data['password'])
                if user is not None:
                    auth_login(request, user)

        return HttpResponseRedirect(reverse('home:home', current_app='home'))
    form = CreateUserForm()
    return render(request, 'signup/signup.html',{'form':form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password'])
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect(reverse('home:home',current_app='home'))
        form = LoginForm()
        return render(request, 'login/login.html',{'form':form,'msg':'username or password are invalid!'})
    form = LoginForm()
    return render(request, 'login/login.html', {'form':form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:home',current_app='home'))

accounts/templates/login/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>PooL</title>
        <meta http-equiv="x-ua-compatible" content="ie=edge">
	      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:400" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'home/assets/icons/css/font-awesome.min.css'%}">
        <link rel="stylesheet" href="{% static 'home/css/style.css'%}">
        <link rel="stylesheet" href="{% static 'home/css/sign_up.css' %}">
    </head>

    <body class="text-center" data-gr-c-s-loaded="true" cz-shortcut-listen="true">
      {% block login %}

      {% endblock %}
      <script src="{% static "home/js/jquery.min.js" %}"></script>
      <script src="{% static "home/js/popper.min.js" %}"></script>
      <script src="{% static "home/js/bootstrap.min.js" %}"></script>
{#        <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>#}
      <script src="{% static "home/js/main.js" %}" type="text/javascript"></script>
    </body>
</html>

accounts/templates/login/login.html
{% extends 'login/base.html' %}
{% block login %}
<form class="form-signin" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
  <!-- <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72"> -->
  <h1 class="h3 mb-3 font-weight-normal"><strong><a class="card-link" href="{% url 'home:home' %}">PooL</a></strong></h1>
  <label for="inputEmail" class="sr-only">Email</label>
    {{ form.email }}
{#  <input name="email" type="email" id="inputEmail" class="form-control edge-bottom" placeholder="email" required autofocus>#}
  <label for="inputPassword" class="sr-only">Password</label>
    {{ form.password }}
{#  <input name="password" type="password" id="inputPassword" class="form-control edge-top" placeholder="Password" required>#}
  <div class="checkbox mb-1">
      <div class="text-danger">{{ msg }}</div>
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
    <a href="#" class="ml-2 text-muted">Forgot your password?</a>
    <div class="h2">
      <a href="#" class="mr-2" style="color:#FF7900"><i class="fa fa-odnoklassniki-square" aria-hidden="true"></i></a>
      <a href="#" class="mr-2" style="color:#5181B8"><i class="fa fa-vk" aria-hidden="true"></i></a>
      <a href="#" style="color:#3B5998"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
    </div>
  </div>
  <button class="btn btn-primary btn-block" type="submit">Sign in</button>
  <a href="{% url 'accounts:signup' %}" class="d-block mt-3 text-muted">Sign up</a>
</form>
{% endblock %}